name: CI/CD Pipeline para EC2

on:
  push:
    branches:
      - main  # Executa o pipeline ao fazer push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Usando Ubuntu como runner do GitHub Actions

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout do código
        uses: actions/checkout@v2

      # Passo 2: Instalar dependências
      - name: Instalar dependências
        run: npm install

      # Passo 3: Fazer deploy para EC2
      - name: Fazer deploy para EC2
        run: |
          # Salvar a chave SSH privada em um arquivo temporário
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > minha-chave
          chmod 600 minha-chave

          # Adicionar o host da EC2 à lista de hosts conhecidos
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          # Fazer o deploy e reiniciar o serviço no EC2
          ssh -i minha-chave -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF

            git pull origin main
            npm install
            pm2 restart all
          EOF

          # Remover a chave temporária
          rm minha-chave
